library(ISLR2)
head(Auto)
lm.fit=lm(mpg~cylinders+displacement+horsepower+weight+acceleration+year+origin,data=Auto)
summary(lm.fit)
names(lm.fit)
coef(lm.fit)
confint(lm.fit)
pairs(Auto)
#3)b)
cor(subset(Auto,select = -name))
#3)c)
lm.fit=lm(mpg~cylinders+displacement+horsepower+weight+acceleration+year+origin,daplot ( horsepower,mpg )ta=Auto)
lm.fitt=lm(mpg~ . -name,data=Auto)
summary(lm.fitt)
#3)d)
par(mfrow=c(2,2))
plot(lm.fitt)
#3)e)
names(Auto)
interact.fit = lm(mpg ~ . -name + horsepower*displacement, data=Auto)
origin.hp = lm(mpg ~ . -name + horsepower*origin, data=Auto)
summary(origin.hp)
inter.fit = lm(mpg ~ . -name + horsepower:origin + horsepower:
                 + horsepower:displacement,
               data=Auto)
summary(inter.fit)
summary(lm(mpg ~ . -name + log(acceleration), data=Auto)) 
summary(lm(mpg ~ . -name + I(horsepower)^2, data=Auto)) 
summary(lm(mpg ~ . -name + I(horsepower), data=Auto))
